---
name: Publish packages
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      # check out the repository source
      - name: checkout
        uses: actions/checkout@v2

      # run the linter
      - name: lint
        run: echo 'TODO - run the linter'

      # compile the Go application
      - name: compile
        run: make
